# Generated by Django 5.2.15 on 2026-06-21 21:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('timing_profile', models.CharField(choices=[('tier_a', 'Tier A (135 min)'), ('tier_c_mvr', 'Tier C MVR (60 min)'), ('tier_c_extended', 'Tier C Extended')], default='tier_c_mvr', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('opening', 'Opening'), ('build', 'Build'), ('evaluation', 'Evaluation'), ('pitching', 'Pitching'), ('deliberation', 'Deliberation'), ('judging', 'Judging'), ('awards', 'Awards'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('opening_at', models.DateTimeField(blank=True, null=True)),
                ('build_start_at', models.DateTimeField(blank=True, null=True)),
                ('build_end_at', models.DateTimeField(blank=True, null=True)),
                ('phase_schedule', models.JSONField(blank=True, default=dict)),
                ('player_count', models.PositiveIntegerField(default=0)),
                ('prompt_revealed', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='events.event')),
            ],
            options={
                'db_table': 'rounds_round',
                'ordering': ('event', 'round_number'),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted_deployed', 'Submitted (deployed)'), ('submitted_failed', 'Submitted (deploy failed)'), ('dnf', 'Did not finish')], default='in_progress', max_length=20)),
                ('git_repo_reference', models.CharField(blank=True, max_length=300)),
                ('deployed_url', models.URLField(blank=True)),
                ('readme_content', models.TextField(blank=True)),
                ('token_budget_used', models.PositiveIntegerField(default=0)),
                ('fuzz_budget_used', models.PositiveIntegerField(default=0)),
                ('attack_surface_coverage', models.CharField(blank=True, choices=[('narrow', 'Narrow'), ('moderate', 'Moderate'), ('broad', 'Broad')], max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='rounds.round')),
            ],
            options={
                'db_table': 'rounds_submission',
                'ordering': ('round', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_type', models.CharField(choices=[('pitch_quality', 'Pitch quality'), ('cross_examination', 'Cross-examination'), ('creative_coherence', 'Creative coherence'), ('ux_quality', 'UX quality'), ('technical_execution', 'Technical execution'), ('documentation', 'Documentation')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('judge_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_given', to='events.eventparticipant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rounds.submission')),
            ],
            options={
                'db_table': 'rounds_score',
                'ordering': ('submission', 'score_type'),
            },
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('event', 'round_number'), name='unique_event_round_number'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('round', 'player'), name='unique_round_player_submission'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('submission', 'judge_participant', 'score_type'), name='unique_submission_judge_scoretype'),
        ),
    ]
