# Generated by Django 5.2.15 on 2026-06-22 15:21

import rounds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='git_repo_reference',
        ),
        migrations.AddField(
            model_name='submission',
            name='archive',
            field=models.FileField(blank=True, max_length=255, upload_to=rounds.models.submission_upload_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='archive_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('submitted_deployed', 'Submitted (deployed)'), ('submitted_failed', 'Submitted (deploy failed)'), ('dnf', 'Did not finish')], default='in_progress', max_length=20),
        ),
    ]
