# Generated by Django 5.2.15 on 2026-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0002_remove_submission_git_repo_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='timing_profile',
            field=models.CharField(choices=[('tier_a', 'Tier A (135 min)'), ('tier_c_mvr', 'Tier C MVR (60 min)')], default='tier_c_mvr', max_length=20),
        ),
    ]
