# Generated by Django 5.2.15 on 2026-08-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0003_alter_round_timing_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='timing_profile',
            field=models.CharField(choices=[('tier_a', 'Tier A'), ('tier_b', 'Tier B (live judging, BYOD)'), ('tier_c_mvr', 'Tier C MVR')], default='tier_c_mvr', max_length=20),
        ),
    ]
