# Generated by Django 5.2.15 on 2026-08-07 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_format_and_more'),
        ('rounds', '0004_alter_round_timing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='slop_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FuzzResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('probe_id', models.CharField(max_length=100)),
                ('bundle', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('outcome', models.CharField(choices=[('slop_detected', 'Slop detected'), ('clean', 'Clean'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('penalty_contributed', models.PositiveIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('contested_reason', models.TextField(blank=True)),
                ('contested_at', models.DateTimeField(blank=True, null=True)),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contested_findings', to='events.eventparticipant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzz_results', to='rounds.submission')),
            ],
            options={
                'db_table': 'rounds_fuzzresult',
                'ordering': ('submission', 'bundle', 'probe_id'),
                'constraints': [models.UniqueConstraint(fields=('submission', 'probe_id'), name='unique_submission_probe')],
            },
        ),
    ]
