# Generated by Django 5.2.15 on 2026-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0005_submission_slop_score_fuzzresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='commit_sha',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
