# Generated by Django 5.2.15 on 2026-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('vibe', 'Vibe'), ('unslop', 'Unslop'), ('underspecified', 'Underspecified')], default='vibe', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='judge_specialization',
            field=models.CharField(blank=True, choices=[('tester', 'Tester'), ('ux_designer', 'UI/UX/HCI'), ('general', 'General engineering'), ('stakeholder', 'Nontech stakeholder')], max_length=20),
        ),
    ]
