# Generated by Django 5.2.15 on 2026-06-16 19:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('tier', models.CharField(choices=[('A', 'Tier A (Verified)'), ('B', 'Tier B (Standard)'), ('C', 'Tier C (Practice)')], default='C', max_length=1)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='unverified', max_length=20)),
                ('mode', models.CharField(choices=[('signup', 'Signup'), ('active', 'Active'), ('archive', 'Archive')], default='signup', max_length=20)),
                ('institutional_affiliation', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'chapters_chapter',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChapterMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roles', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'chapters_membership',
            },
        ),
    ]
