# Generated by Django 5.2.15 on 2026-06-22 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_rename_chaptermembership_to_chapterstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterstaff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_staff_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterstaff',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='chapterstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
