# Generated by Django 5.2.15 on 2026-06-21 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('chapter', 'Chapter'), ('regional', 'Regional')], max_length=20)),
                ('scope_reference_id', models.UUIDField(blank=True, null=True)),
                ('period', models.CharField(choices=[('current_season', 'Current season'), ('persistent', 'Persistent'), ('all_time', 'All time')], max_length=20)),
                ('season_year', models.PositiveIntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('rank_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('events_competed', models.PositiveIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rankings_ranking',
                'ordering': ('scope', 'period', 'rank'),
                'constraints': [models.UniqueConstraint(fields=('user', 'scope', 'scope_reference_id', 'period', 'season_year'), name='unique_ranking_slot')],
            },
        ),
    ]
